name: "Lint PR title"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint_pr_title:
      uses: ultimateai/workflows/.github/workflows/lint-pr.yml@0.10.0
      secrets: inherit
      with:
        subjectPattern: ([-a-zA-Z0-9]{2,5}[/-]{1}[0-9]+.*) # PR Title example: minor: PLT-239 description. This subject pattern enforces the existance of a Jira issue after the type_word. 
        subjectPatternError: 'The subject "{subject}" found in the pull request title "{title}" did not match the configured pattern. Please start with the jira issue which originated your work - like feat(scope): PLT-000 additional info'
        requireScope: false
        allowed_types: |
          fix
          feat
          breaking
          minor
          major
          patch